### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by bsinner** [fiveSpeedMazdarati/brewMeister#1]
# Design/Code Review 1

### Reviewer: Blake

|Item |Considerations| Comments/Suggestions|
|--------|---------|---|
|||Reviewer comments and suggestions go here. Each item should have *at least* one "kudos" and two suggestions for improvement|
|**Problem Statement**|1. Accurately describes project purpose<br> 2. Is professional and free of typos, slang, etc.<br> 3. Fully explains the problem and the solution<br> 4. Is understandable by the average person| Problem statement is clear and easy to understand,  maybe add more information about how the Brewmeister tracks brews and keeps information, and the advantages it has over other brewing software. |
|**Design Documentation**|1. Navigation/flow through the application is logical and easy to use. <br>2. The order in which values are displayed are logical and easy to understand/use <br>3. The order in which the form fields entered are logical and easy to understand/use<br>4. All data discussed/documented (problem statement, flow, db design, etc.) is represented on the screens | Overall the flow of the application is well thought out and easy to use, could add an optional cap color field on the create page,  and maybe admin screens. |
|**Data model/Database**|1. Everything on the screens and problem statement/flow is represented in the model <br> 2. There is at least one 1-to-many relationship.<br> 3. The model represents good database design <br>| The models are good database design and represent everything on the screens except for the cap color, and some javadoc comments are missing. |
|**Code**|1. Proper Maven project structure is used<br> 2. a .gitignore file for IntelliJ Java projects has been implemented <br> 3. There is not any redundant or copy/paste code in the JSPs or classes<br> 4. Classes are appropriately-sized (no monster classes)<br> Property files are used appropriately: no hard-coded values <br> 5. Logging statements are used rather than System.out.println and printStackTrace.<br> 6. There are appropriate unit tests/code coverages.  | Kudos on thoroughly testing all of the DAO methods, the test database class could be improved by adding the driver name to a properties file, also in UserDAOTest the user is named bookToDelete and the word book appears in the comments. |

**Comment by fiveSpeedMazdarati** [comment]
Thank you, Blake! I did not notice my copypaste error in UserDaoTest. I'll correct that straightaway.
