### ISSUE TITLE
Instructor Feedback - Week 5

### ISSUE THREAD

**Issue by pawaitemadisoncollege** [fiveSpeedMazdarati/brewMeister#2]
Nice job with the hibernate one-to-manies. Good to see you using .equals() for your comparisons.

- [ ] update comments and variable names for your project https://github.com/fiveSpeedMazdarati/brewMeister/blob/24b4bc8f5ad378dfb134153d8c936593e3d79950/src/test/java/com/lukebusch/persistence/UserDAOTest.java#L121-L128
- [ ] be sure to test the case for deleting a user that has batches - are they batches deleted? Should they be deleted? Test it!
- [ ] remove the obsolete directory - you can always get these back from git history :)

**Comment by fiveSpeedMazdarati** [comment]
Yeah, I realized just before you posted this issue that I'd been the victim of my own copypaste.
Good point on the obsolete directory...I really never meant to commit it to the repository. Apparently, I failed to add it to the .gitignore file. 
I'll add a test for deleting a user with batches.

**Comment by fiveSpeedMazdarati** [comment]
I suppose I could use the .equals() comparison here as well and just compare the object before the update and the object after the update. That may be easier to read. Maybe not.

https://github.com/fiveSpeedMazdarati/brewMeister/blob/24b4bc8f5ad378dfb134153d8c936593e3d79950/src/test/java/com/lukebusch/persistence/UserDAOTest.java#L57-L76
